class Keys():
    id = 'id'
    text = 'overview'
    title = 'title'
    count = 'vote_count'
    avarage = 'vote_average'
    score = 'score'
    cast = 'cast'
    crew = 'crew'
    director = 'director'
    keywords = 'keywords'
    genres = 'genres'
    soup = 'soup'